import { MetadataRoute } from "next";

// Static routes with realistic lastModified dates
const staticRoutes: { path: string; lastmod: string; changefreq: "weekly" | "monthly"; priority: number }[] = [
  { path: "", lastmod: "2026-06-13", changefreq: "weekly", priority: 1.0 },
  { path: "/about", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.7 },
  { path: "/factory", lastmod: "2026-06-23", changefreq: "monthly", priority: 0.9 },
  { path: "/products", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.8 },
  { path: "/products/paper-boxes", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.8 },
  { path: "/products/paper-bags", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.8 },
  { path: "/products/subscription-boxes", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.8 },
  { path: "/industries", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.7 },
  { path: "/industries/candles-fragrance", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.8 },
  { path: "/industries/jewelry", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.8 },
  { path: "/industries/chocolate-confectionery", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.8 },
  { path: "/industries/stationery-gifts", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.8 },
  { path: "/industries/tea-beverages", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.8 },
  { path: "/industries/pet-subscription", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.8 },
  { path: "/industries/cosmetics-beauty", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.8 },
  { path: "/industries/wine-spirits", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.8 },
  { path: "/industries/apparel-fashion", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.8 },
  { path: "/industries/bakery-food", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.8 },
  { path: "/industries/cbd-hemp", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.8 },
  // v3.0 Target Industries (5 core focus pages)
  { path: "/industries/beauty-skincare", lastmod: "2026-07-02", changefreq: "weekly", priority: 0.9 },
  { path: "/industries/fragrance-candles", lastmod: "2026-07-02", changefreq: "weekly", priority: 0.9 },
  { path: "/industries/corporate-gifts-subscription", lastmod: "2026-07-02", changefreq: "weekly", priority: 0.9 },
  { path: "/industries/stationery-toys", lastmod: "2026-07-02", changefreq: "weekly", priority: 0.9 },
  { path: "/industries/jewelry-accessories", lastmod: "2026-07-02", changefreq: "weekly", priority: 0.9 },
  { path: "/contact", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.6 },
  { path: "/glossary", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.6 },
  { path: "/eco", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.7 },
  { path: "/blog", lastmod: "2026-06-12", changefreq: "weekly", priority: 0.7 },
  { path: "/blog/switch-plastic-to-paper-packaging-dtc-guide", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/unboxing-experience-drives-dtc-growth", lastmod: "2025-05-28", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/eco-packaging-guide-dtc-brands-2025", lastmod: "2025-05-15", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/subscription-box-packaging-design", lastmod: "2025-04-30", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/custom-packaging-low-moq-guide", lastmod: "2025-04-12", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/packaging-impacts-product-reviews", lastmod: "2025-03-25", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/kraft-paper-vs-coated-paper", lastmod: "2025-03-10", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/china-vs-us-packaging-manufacturer", lastmod: "2026-06-05", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/custom-packaging-cost-guide", lastmod: "2026-05-20", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/eco-packaging-roi-small-dtc-brands", lastmod: "2026-06-12", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/custom-packaging-for-startups-guide", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/import-custom-packaging-from-china-guide", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/biodegradable-ecommerce-packaging-guide", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/branded-packaging-ideas-ecommerce", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/digital-printing-vs-offset-packaging", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/compostable-packaging-alternatives", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.6 },
  { path: "/compare/rigid-vs-corrugated-boxes", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.7 },
  { path: "/compare/bupack-vs-arka", lastmod: "2026-06-23", changefreq: "monthly", priority: 0.8 },
  { path: "/compare/bupack-vs-packlane", lastmod: "2026-06-23", changefreq: "monthly", priority: 0.8 },
  { path: "/case-studies", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.7 },
  { path: "/case-studies/makeup-brush-brand-launch", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.7 },
  { path: "/case-studies/fragrance-gift-box-600-sales", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.7 },
  { path: "/case-studies/wine-diy-modular-packaging", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.7 },
  { path: "/moq-guide", lastmod: "2026-06-07", changefreq: "monthly", priority: 0.7 },
  { path: "/fsc-certified-packaging", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.8 },
  { path: "/products/folding-cartons", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.8 },
  { path: "/products/rigid-gift-boxes", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.8 },
  { path: "/services/design-support", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.7 },
  { path: "/services/sampling-prototyping", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.7 },
  { path: "/faq", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/custom-boxes-overseas-manufacturer", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/how-to-create-unboxing-experience", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/eco-friendly-packaging-small-business", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.6 },
  // New product & resource pages
  { path: "/products/custom-mailer-boxes", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.8 },
  { path: "/products/custom-paper-bags", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.8 },
  { path: "/packaging-101", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.8 },
  // Guide index & GEO content
  { path: "/guide", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.8 },
  { path: "/guide/ecommerce-packaging-sourcing", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.9 },
  // New blog posts (GEO comparison articles)
  { path: "/blog/top-10-custom-packaging-suppliers-2025", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/china-vs-us-packaging-manufacturer-compared", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/packaging-design-trends-2026", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/custom-packaging-timeline-guide", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/kraft-vs-coated-paper-deep-dive", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/custom-packaging-cost-breakdown", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/seasonal-packaging-strategy", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/packaging-for-subscription-boxes-guide", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/why-fsc-certification-matters-packaging", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.6 },
  // Week 26 new blog posts
  { path: "/blog/how-to-evaluate-packaging-suppliers-checklist", lastmod: "2026-06-24", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/custom-supplement-packaging-guide", lastmod: "2026-06-21", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/custom-electronics-packaging-guide", lastmod: "2026-06-22", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/custom-coffee-packaging-guide", lastmod: "2026-06-27", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/sustainable-packaging-trends-2026", lastmod: "2026-06-27", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/custom-tea-packaging-guide", lastmod: "2026-06-29", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/luxury-packaging-design-guide", lastmod: "2026-06-29", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/custom-chocolate-packaging-guide", lastmod: "2026-06-30", changefreq: "monthly", priority: 0.6 },
  { path: "/blog/custom-jewelry-packaging-guide", lastmod: "2026-06-30", changefreq: "monthly", priority: 0.6 },
  { path: "/privacy", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.3 },
  { path: "/terms", lastmod: "2026-06-13", changefreq: "monthly", priority: 0.3 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://www.bupackeco.com";

  return staticRoutes.map((route) => ({
    url: `${baseUrl}${route.path}`,
    lastModified: new Date(route.lastmod),
    changeFrequency: route.changefreq,
    priority: route.priority,
  }));
}
